### ISSUE TITLE
No Readme 

### ISSUE THREAD

**Issue by beaussart** [DowanBeer/NoSteakNoBreak#1]
Il n'y a pas de Readme et je sais pas ce que c'est le projet !

**Comment by Plinz** [comment]
Le mec trop au taqué

**Comment by beaussart** [comment]
Le Readme n'est pas très explicite

**Comment by Plinz** [comment]
Pas besoin de l'être pour l'instant :) on est qu'en pré-dev.
Quand on aura plus réfléchit on en fera un beau et complet avec un wiki si quelqu'un est motivé !

**Comment by dowan** [comment]
Bon c'est pas bientôt fini le sam la!!

**Comment by Plinz** [comment]
Le sam c'est pas le mec qui se fait chier en soirée ?
